### ISSUE TITLE
Parse configuration into request queue

### ISSUE THREAD

**Issue by obfuscurity** [obfuscurity/quarbon#4]

**Comment by obfuscurity** [comment]
Sample configuration:

```
groups:
- name: ServerHealth
  rules:
  - alert: CollectdLoadHigh
    expr:  target=collectd.*.load.load.longterm
    for: 5m
    aggregate: avg
    thresholds:
    - high: 40
    labels:
      exporter: collectd
      variables:
        hostname: /collectd.(.*).load.load.longterm/
    annotations:
      summary: 'A host is reporting high load.'
      description: '{{ hostname }} reporting a(n) {{ threshold }} {{ aggregate }} load of {{ value }}.'
      runbook: 'https://github.com/obfuscurity/quarbon/wiki/Runbooks#host-load'
```
